ft-readmorepage
martinemahirwe/My-portifolio pull request #2
Opened 2023-05-26 08:33 UTC by martinemahirwe

### What does this PR do?

- Adds readmore page with iresponsiveness

### Description of Task to be completed

- writing more details about blogs, details
- Creating comments section
- posting latest comments
- making responsive webdesigns for 4 different css breakpoints

### How should this manually be tested?

- Download this repo and open `readmore.html `

2023-06-05 06:58 UTC, wakaflorien requested changes

2023-06-05 06:58 UTC, wakaflorien commented on .gitignore
> +
- same here. css files should not be ignored.

2023-06-05 13:25 UTC, martinemahirwe commented
okay let me do it


On Mon, Jun 5, 2023 at 8:58 AM FLORIEN NIYONGABO ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In .gitignore
> <https://github.com/martinemahirwe/My-portifolio/pull/2#discussion_r1217611425>
> :
>
> > @@ -1,8 +1,5 @@
> -blogs.css
> +
>
>
>    - same here. css files should not be ignored.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/martinemahirwe/My-portifolio/pull/2#pullrequestreview-1461835342>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6EJ4MCILIG5B7VPA4KH3YDXJV7RBANCNFSM6AAAAAAYP5EQYY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-06-06 06:36 UTC, wakaflorien approved these changes

2023-06-06 06:47 UTC, wakaflorien requested changes
- This page needs some improvements, spacing, image size, blog title is not aligned with the rest of the blog content
![image](https://github.com/martinemahirwe/My-portifolio/assets/48131185/f03cad5c-5e6c-4eac-8713-9ca7ec27c5e5)

- same here for readmore

![Screenshot from 2023-06-06 08-44-14](https://github.com/martinemahirwe/My-portifolio/assets/48131185/14927062-36af-4bad-b2e6-ff21fbc43d0a)

2023-06-08 16:06 UTC, closed without merging